### ISSUE TITLE
Import gives ApiError, ApiThrottledError, ApiBadRequestError

### ISSUE THREAD

**Issue by zuhaagha** [Clarifai/Clarifai_py#6]
Hi

I am trying to use the ClarifaiApi to tag images using the Python client and I receive the following error when I try to import ClarifaiApi.

Traceback (most recent call last):
    from clarifai.client import ClarifaiApi
  File "C:\Python34\lib\site-packages\clarifai\client\__init__.py", line 3, in <module>
    from .client import ClarifaiApi, ApiError, ApiThrottledError, ApiBadRequestError
  File "C:\Python34\lib\site-packages\clarifai\client\client.py", line 5
    except Exception, e:
                    ^
SyntaxError: invalid syntax

I can't seem to find any documentation related to this error. Any help would be appreciated.

**Comment by robertwenquan** [comment]
This error is due to the syntax error of exception handling in written in Python2 grammar running in Python3.
If you switch to Python2.7 you could be able to play with the API as documented.

**Comment by zuhaagha** [comment]
Yeah I just figured that out after some googling. Thank you! I will switch to Python 2.7.

Sent from my iPhone

On Jul 5, 2015, at 11:27 PM, Robert Wen <notifications@github.com<mailto:notifications@github.com>> wrote:


This error is due to the syntax error of exception handling in written in Python2 grammar running in Python3.
If you switch to Python2.7 you could be able to play with the API as documented.

-
